### ISSUE TITLE
Running project problem

### ISSUE THREAD

**Issue by hramezani** [pesarkhobeee/WUIChiBashi#1]
I think below line should be removed from running commands and move to initial environment section.
`python -m pip install -r requirements.txt`

Because when you create a environment, you can install the required packages. if you run the install command again nothing happens because the packages already installed.

**Comment by pesarkhobeee** [comment]
Well I can see your point but we are talking about "Development Environment" which means there is a possibility that a developer changes the "requirements.txt" file so I prefer to hold it there,  I think it is better to have this checking each time that you want to enter to the development environment :)

**Comment by hramezani** [comment]
I think it should be in the `Development Environment` section. and also the enable virtual env command should be there. because these commands are related to the environment.
At least `every time that you want to run` the project you do not enable the environment again

**Comment by pesarkhobeee** [comment]
Actuality, it is in the `Development Environment` and I have already separated how you should run this program in production and development mode in the readme 

![screenshot from 2019-02-19 09-21-02](https://user-images.githubusercontent.com/147461/53000281-4c014a80-3428-11e9-9a0b-d11942f2ffd8.png)

So at least from my point of view, the readme file is clear in this section but I will be happy if you describe your opinion by an example.
