### ISSUE TITLE
Problem in project running

### ISSUE THREAD

**Issue by hramezani** [pesarkhobeee/WUIChiBashi#3]
I tried to run the project based on your instruction, but I couldn't run it.
Could you please clone the project from scratch and run it.

**Comment by pesarkhobeee** [comment]
Dear @hramezani thanks for testing this project, but as you can see in the attached screenshot I have installed a fresh Linux on the virtual machine and I didn't have any problem, so would you please tell me what is your operating system and which version exactly it is? 


![screenshot from 2019-02-18 19-25-03](https://user-images.githubusercontent.com/147461/52973204-94cfe980-33bd-11e9-9378-98d595bc2d75.png)

**Comment by hramezani** [comment]
it is something related to my machine. Thank you for the reply
